org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
minecraft_version=1.21.11
arch_plugin_version=3.5.168
arch_loom_version=1.14.476
shadow_version=9.5.1
loader_version=0.18.3
fabric_version=0.140.0+1.21.11
neoforge_version=21.11.42
mod_version=1.3.2
maven_group=com.autoshulker
archives_base_name=auto_shulker_inventory
modmenu_version=17.0.0
cloth_config_version=21.11.153
