org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
minecraft_version=1.21.8
arch_plugin_version=3.5.168
arch_loom_version=1.14.476
shadow_version=9.5.1
loader_version=0.18.3
fabric_version=0.136.1+1.21.8
neoforge_version=21.8.53
mod_version=1.4.0
maven_group=de.dennisthegamer.autoshulkerinventory
archives_base_name=auto_shulker_inventory
modmenu_version=15.0.0
yacl_version=3.8.1+1.21.6
