modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/DennisTheGamer/auto-shulker-inventory/issues"

[[mods]]
modId = "inventory_shulker"
version = "${version}"
displayName = "Auto Shulker Inventory"
displayURL = "https://modrinth.com/mod/auto-shulker-inventory"
logoFile = "assets/inventory_shulker/icon.png"
authors = "Dennis_thegamer"
description = '''Automatically stores items in shulker boxes when inventory is full. Compatible with Minecraft 1.21.9 through 1.21.11'''

[[mixins]]
config = "inventory_shulker.mixins.json"

[[dependencies.inventory_shulker]]
modId = "neoforge"
type = "required"
versionRange = "[21.9,21.12)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inventory_shulker]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,1.21.12)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inventory_shulker]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.8.0,)"
ordering = "NONE"
side = "CLIENT"
